const MESSAGES: Record<string, string> = {
  NOT_AUTHORIZED: 'No tienes permiso para realizar esta acción.',
  INVALID_INPUT: 'Revisa que los datos estén completos.',
  INVALID_CREDENTIALS: 'Correo o contraseña incorrectos.',
  NO_ACTIVE_EDITION: 'El evento aún no está disponible.',
  THEME_LOCKED: 'La temática está bloqueada porque el evento está en operación real.',
  INVALID_THEME: 'La configuración de la temática no es válida.',
  THEME_TOO_LARGE: 'La configuración de la temática es demasiado grande.',
  INVALID_ASSET_PATH: 'Las rutas de imágenes deben empezar con /assets/ o https://.',
  NO_DRAFT: 'No hay un borrador para publicar.',
  NOT_FOUND: 'No se encontró el elemento.',
  INVALID_TRANSITION: 'El estado de la propuesta cambió. Actualiza la página e inténtalo de nuevo.',
  VALIDATION_FAILED: 'Revisa los campos del taller antes de guardar.',
  INVALID_PAYLOAD: 'Los datos del taller no son válidos. Actualiza la página e inténtalo de nuevo.',
  CAREERS_REQUIRED: 'Elige al menos una carrera relacionada.',
  DUPLICATE_CAREER: 'No repitas carreras relacionadas.',
  PUBLISH_STATE_INCONSISTENT: 'La propuesta y la actividad publicada no coinciden. Contacta a soporte antes de intentarlo de nuevo.',
  FEEDBACK_REQUIRED: 'Escribe el mensaje para el tallerista antes de solicitar cambios.',
  NOTES_REQUIRED: 'Escribe las notas internas antes de guardarlas.',
  TEXT_TOO_LONG: 'El texto no puede superar 5000 caracteres.',
  INVALID_FILTER: 'Revisa los filtros de la bandeja.',
  NOT_IN_REAL_OPERATION: 'El desbloqueo de emergencia solo aplica durante la operación real.',
  WRONG_PHRASE: 'La frase de confirmación no coincide.',
  RESET_DISABLED: 'El ambiente ya está en operación real y no se puede reiniciar.',
  TEMPORARY_RECORDS_REMAIN: 'Aún quedan elementos temporales en el ambiente. Reinicia la preparación antes de activar la operación real.',
  AUTH_CLEANUP_PENDING: 'Completa la limpieza de accesos de participantes antes de activar la operación real.',
  INVALID_ACTION: 'La acción solicitada no está disponible.',
  REASON_REQUIRED: 'Escribe un motivo de al menos 10 caracteres.',
  PURGE_DISABLED: 'La limpieza de datos de prueba está deshabilitada en operación real.',
  PURGE_BLOCKED: 'Hay datos reales ligados a datos de prueba. Resuélvelos antes de limpiar.',
  ALREADY_REAL: 'La operación real ya está activa.',
  DEMO_DATA_REMAINS: 'Aún quedan elementos temporales en el ambiente. Reinicia la preparación antes de activar la operación real.',
  NO_PUBLISHED_THEME: 'Publica una temática antes de activar la operación real.',
  INTERESTS_CLOSED: 'La selección de carreras ya cerró.',
  INTERESTS_NOT_AVAILABLE: 'Esta pregunta se habilita después de participar en el evento.',
  TOO_MANY_INTERESTS: 'Puedes elegir máximo tres carreras.',
  DUPLICATE_INTEREST: 'No repitas carreras.',
  INVALID_CAREER: 'La licenciatura elegida ya no está disponible. Elige otra.',
  INVALID_HIGH_SCHOOL: 'Elige una preparatoria activa del catálogo.',
  HIGH_SCHOOL_EXISTS: 'Ya existe una preparatoria con ese nombre.',
  UNRESOLVED_HIGH_SCHOOLS: 'Relaciona todas las preparatorias no reconocidas antes de cargar el padrón.',
  INVALID_STAFF_CREDENTIALS: 'Correo o contraseña incorrectos.',
  NETWORK: 'No hay conexión. Revisa tu internet e inténtalo de nuevo.',
  WEAK_PASSWORD: 'La contraseña debe tener al menos 10 caracteres.',
  PASSWORD_MISMATCH: 'Las contraseñas no coinciden.',
  INVALID_EMAIL: 'Escribe un correo válido.',
  INVALID_NAME: 'Escribe un nombre válido.',
  INVALID_PHONE: 'El teléfono debe tener entre 10 y 15 dígitos.',
  CONSENT_REQUIRED: 'Para continuar, acepta el Aviso de Privacidad.',
  EMAIL_EXISTS: 'Este correo ya está registrado.',
  INVALID_PASSWORD: 'La contraseña debe tener entre 8 y 72 caracteres.',
  ACCESS_ALREADY_CONFIGURED: 'Este correo ya tiene una contraseña. Inicia sesión con ella.',
  INVALID_GRADE: 'Elige tu grado.',
  INVALID_PERIOD: 'Elige el periodo en el que te interesa ingresar.',
  TOO_MANY_ROWS: 'El archivo tiene demasiadas filas. Divídelo en partes más pequeñas.',
  INVALID_CODE: 'El código solo puede tener letras, números, guiones y guion bajo (2 a 40).',
  CODE_EXISTS: 'Ya existe un elemento con ese código.',
  INVALID_DIVISION: 'Elige una división válida.',
  ACTIVITY_EXISTS: 'Ya existe un taller con ese nombre en la división.',
  SESSION_EXISTS: 'Ese taller ya tiene un horario a esa hora.',
  INVALID_TIMES: 'La hora de fin debe ser posterior a la de inicio.',
  INVALID_CAPACITY: 'El cupo debe estar entre 1 y 2000.',
  HAS_ATTENDANCES: 'No se puede borrar porque ya tiene asistencias registradas.',
  REASON_REQUIRED_SHORT: 'Escribe el motivo (al menos 5 caracteres).',
  INVALID_ROLES: 'Elige al menos un rol.',
  CANNOT_DEACTIVATE_SELF: 'No puedes desactivar tu propia cuenta.',
  LAST_COORDINATOR: 'Debe quedar al menos una cuenta de Coordinación activa.',
  PRIVACY_NOTICE_REQUIRED: 'Primero acepta el Aviso de Privacidad para continuar.',
  INVALID_SESSION_STATUS: 'Elige un estado válido para el horario.',
  CSV_EMPTY: 'El archivo no tiene filas.',
  ROSTER_OFFICIAL: 'El padrón ya es oficial. La carga de Forms está bloqueada; solo Coordinación puede reabrirla.',
  ROSTER_ALREADY_OFFICIAL: 'El padrón ya estaba declarado como oficial.',
  ROSTER_NOT_OFFICIAL: 'El padrón no está declarado como oficial.',
  UNRESOLVED_CAREERS: 'Relaciona todas las carreras no reconocidas antes de cargar el padrón.',
  PHONE_REQUIRED: 'El teléfono es obligatorio.',
  HIGH_SCHOOL_REQUIRED: 'Elige tu escuela o preparatoria.',
  CAREER_REQUIRED: 'Elige la licenciatura de tu interés.',
  CSV_UNREADABLE: 'No se pudo leer el archivo. Verifica que sea un CSV.',
  RESERVATIONS_NOT_OPEN: 'Las reservaciones todavía no abren.',
  RESERVATIONS_CLOSED: 'Las reservaciones ya cerraron. Aún puedes cancelar mientras tu sesión no termine.',
  SESSION_UNAVAILABLE: 'Este horario ya no está disponible. Elige otra sesión.',
  SESSION_CANCELLED: 'Este horario fue cancelado. Elige otra sesión.',
  SESSION_ENDED: 'Esta sesión ya terminó.',
  CURRENT_SESSION_ENDED: 'Tu sesión actual ya terminó; ya no puedes cambiarla.',
  ALREADY_ATTENDED: 'Ya registraste asistencia en este taller.',
  SESSION_FULL: 'Ese horario acaba de llenarse. Elige otra sesión.',
  MAX_RESERVATIONS: 'Ya alcanzaste el máximo de talleres. Cancela uno para elegir otro.',
  SAME_WORKSHOP: 'Ya tienes este taller en tu ruta. Usa "Cambiar" para elegir otro horario.',
  SCHEDULE_CONFLICT: 'Se empalma con otra sesión de tu ruta.',
  ALREADY_RESERVED: 'Ya tienes reservada esta sesión.',
  RESERVATION_NOT_FOUND: 'Esa reservación ya no está vigente. Actualiza tu ruta.',
  SESSION_TIMES_LOCKED: 'Este horario ya tiene reservaciones: no se puede mover. Crea un horario nuevo y cancela este.',
  CAPACITY_BELOW_RESERVED: 'El cupo no puede ser menor que las reservaciones vigentes.',
  LOCATION_CHANGE_NEEDS_CONFIRMATION: 'Este horario tiene reservaciones. Usa "Cambiar ubicación" para moverlo con aviso.',
  HAS_RESERVATIONS: 'Tiene reservaciones registradas. Cancélalo en lugar de eliminarlo.',
  INVALID_CREDITS: 'Los sellos deben estar entre 1 y 10.',
  INVALID_WINDOW: 'El cierre debe ser posterior a la apertura.',
  LOCATION_REQUIRED: 'Escribe la nueva ubicación.',
  INVALID_CREDENTIAL: 'El código o QR no es válido. Verifica con el facilitador.',
  NO_RESERVATION: 'No tienes reservación para esta sesión.',
  ALREADY_CHECKED_IN: 'Esta asistencia ya estaba registrada.',
  CREDENTIAL_GENERATION_FAILED: 'No se pudo generar una credencial nueva. Intenta de nuevo.',
  INVALID_ACTIVITY_TYPE: 'El tipo de actividad debe ser académica o liderazgo.',
  INVALID_REQUIREMENTS: 'Los requisitos deben ser números válidos.',
  INVALID_QUANTITY: 'La cantidad debe ser un número válido.',
  CATEGORY_INACTIVE: 'Esta categoría de sorteo está inactiva.',
  PENDING_SELECTION: 'Ya hay un ganador pendiente de confirmar para este premio. Confírmalo o márcalo como no presentado.',
  PRIZE_EXHAUSTED: 'Este premio ya no tiene unidades disponibles.',
  POOL_EMPTY: 'No hay candidatos en el pool para este sorteo.',
  INVALID_STATUS: 'El estado del ganador no permite esta acción.',
  PRIZE_INACTIVE: 'Este premio está inactivo y no se puede sortear.',
  DEMO_REAL_MISMATCH: 'No se puede mover un premio entre entornos de prueba y real.',
  QUANTITY_BELOW_COMMITTED: 'La cantidad no puede ser menor que las unidades ya comprometidas (entregadas o seleccionadas).',
};

const GENERIC = 'Algo salió mal. Inténtalo de nuevo.';

export function friendlyError(cause: unknown): string {
  console.error(cause);
  const raw =
    typeof cause === 'string'
      ? cause
      : cause && typeof cause === 'object' && 'message' in cause
        ? String((cause as { message: unknown }).message)
        : '';
  return MESSAGES[raw] ?? GENERIC;
}
