import type { ThemeConfig } from './types';

export const neutralTheme: ThemeConfig = {
  meta: {
    eventName: 'Día OV',
    editionLabel: '',
    tagline: 'Orientación vocacional',
    taglineHighlight: '',
    organizer: 'Universidad Anáhuac Cancún',
    guideName: 'Leonel',
  },
  colors: {
    primary: '#FF5900',
    secondary: '#1D6FD8',
    accent: '#0E9384',
    success: '#16A34A',
    warning: '#D97706',
    error: '#DC2626',
    neutral: '#64748B',
    background: '#F6F7F9',
    surface: '#FFFFFF',
    surfaceRaised: '#FFFFFF',
    ink: '#111827',
    inkMuted: '#4B5563',
    line: '#E5E7EB',
  },
  typography: { display: 'Montserrat', body: 'Inter' },
  radius: 12,
  style: { background: 'plain', glowRing: false, metallicTitles: false },
  assets: {
    logoMark: '/assets/images/Logo_A.png',
    logoWordmark: '/assets/images/Logo_Anahuac_NRA_Licenciaturas.png',
    logoSeal: '/assets/images/Logo_Anáhuac_Cancún_Vertical.png',
    logoTagline: '/assets/images/the-international-university.svg',
    mascot: '',
  },
  vocabulary: {
    activity: { one: 'Misión', many: 'Misiones' },
    division: { one: 'División', many: 'Divisiones' },
    rank: { one: 'Nivel', many: 'Niveles' },
    passport: { one: 'Bitácora de Explorador', many: 'Bitácoras de Explorador' },
    route: { one: 'Mi ruta', many: 'Mis rutas' },
    stamp: { one: 'Sello', many: 'Sellos' },
    interests: { one: 'Carrera de interés', many: 'Carreras de interés' },
  },
  ranks: [
    { name: 'Nivel 1', description: 'Comenzaste tu recorrido.', promotion: 'Comenzaste tu recorrido.' },
    { name: 'Nivel 2', description: 'Ya completaste tu primera misión.', promotion: 'Subiste al nivel 2.' },
    { name: 'Nivel 3', description: 'Ya llevas dos misiones completadas.', promotion: 'Subiste al nivel 3.' },
    { name: 'Nivel 4', description: 'Tu recorrido va muy avanzado.', promotion: 'Subiste al nivel 4.' },
    { name: 'Nivel 5', description: 'Completaste el recorrido.', promotion: 'Alcanzaste el nivel máximo.' },
  ],
  texts: {
    navPassport: 'Bitácora',
    navActivities: 'Misiones',
    navInterests: 'Intereses',
    loginTitle: 'Bienvenido al Día OV',
    loginSubtitle: 'Escribe tu correo electrónico para continuar.',
    loginHelp: 'Si no recuerdas tu contraseña, pide apoyo al personal del evento.',
    welcomeTitle: 'Hola, {name}',
    welcomeBody: 'Antes de empezar, revisa y acepta el Aviso de Privacidad.',
    passportIntro: 'Aquí verás tu avance durante el evento.',
    progressNext: 'Te faltan {activities} {activityTerm} para llegar a {rank}.',
    progressMax: 'Llegaste al nivel máximo.',
    activitiesIntro: 'Las misiones son los talleres de Día OV. Consulta sus horarios.',
    activitiesEmpty: 'Aún no hay misiones publicadas.',
    interestsPromptTitle: '¿Qué carreras te interesaron más?',
    interestsPromptBody: 'Selecciona hasta 3 carreras que hoy llamaron más tu atención. No tienen que ser las mismas que elegiste antes del evento.',
    interestsTitle: '¿Qué carreras te interesaron más?',
    interestsBody: 'Selecciona hasta 3 carreras que hoy llamaron más tu atención. No tienen que ser las mismas que elegiste antes del evento.',
    interestsSaved: 'Gracias. Guardamos tus intereses.',
    interestsClosed: 'La selección de carreras ya cerró. Aquí puedes consultar lo que respondiste.',
    closingTitle: 'Gracias por participar',
    closingBody: 'Gracias por participar en el Día OV. Tus carreras de interés quedaron guardadas.',
  },
  divisions: {},
};
