import type { ThemeConfig } from './types';

export const neutralTheme: ThemeConfig = {
  meta: {
    eventName: 'Día OV',
    editionLabel: '',
    tagline: 'Orientación vocacional',
    taglineHighlight: '',
    organizer: 'Universidad Anáhuac Cancún',
    guideName: 'Leonel',
  },
  colors: {
    primary: '#FF5900',
    secondary: '#1D6FD8',
    accent: '#0E9384',
    success: '#16A34A',
    warning: '#D97706',
    error: '#DC2626',
    neutral: '#64748B',
    background: '#F6F7F9',
    surface: '#FFFFFF',
    surfaceRaised: '#FFFFFF',
    ink: '#111827',
    inkMuted: '#4B5563',
    line: '#E5E7EB',
  },
  typography: { display: 'Montserrat', body: 'Inter' },
  radius: 12,
  style: { background: 'plain', glowRing: false, metallicTitles: false },
  assets: {
    logoMark: '/assets/images/Logo_A.png',
    logoWordmark: '/assets/images/Logo_Anahuac_NRA_Licenciaturas.png',
    logoSeal: '/assets/images/Logo_Anáhuac_Cancún_Vertical.png',
    logoTagline: '/assets/images/the-international-university.svg',
    mascot: '',
  },
  vocabulary: {
    activity: { one: 'Taller', many: 'Talleres' },
    division: { one: 'División', many: 'Divisiones' },
    rank: { one: 'Nivel', many: 'Niveles' },
    passport: { one: 'Pasaporte', many: 'Pasaportes' },
    route: { one: 'Mi ruta', many: 'Mis rutas' },
    stamp: { one: 'Sello', many: 'Sellos' },
    interests: { one: 'Carrera de interés', many: 'Carreras de interés' },
  },
  ranks: [
    { name: 'Nivel 1', description: 'Comenzaste tu recorrido.', promotion: 'Comenzaste tu recorrido.' },
    { name: 'Nivel 2', description: 'Ya participaste en tu primer taller.', promotion: 'Subiste al nivel 2.' },
    { name: 'Nivel 3', description: 'Exploras distintas divisiones.', promotion: 'Subiste al nivel 3.' },
    { name: 'Nivel 4', description: 'Tu recorrido va muy avanzado.', promotion: 'Subiste al nivel 4.' },
    { name: 'Nivel 5', description: 'Completaste el recorrido.', promotion: 'Alcanzaste el nivel máximo.' },
  ],
  texts: {
    navPassport: 'Pasaporte',
    navActivities: 'Talleres',
    navInterests: 'Intereses',
    loginTitle: 'Bienvenido al Día OV',
    loginSubtitle: 'Ingresa con el correo de tu registro y tu fecha de nacimiento.',
    loginHelp: 'Si no te registraste antes del evento, acércate al módulo de registro.',
    welcomeTitle: 'Hola, {name}',
    welcomeBody: 'Antes de empezar, revisa y acepta el Aviso de Privacidad.',
    passportIntro: 'Aquí verás tu avance durante el evento.',
    progressNext: 'Te faltan {activities} {activityTerm} y {divisions} {divisionTerm} para llegar a {rank}.',
    progressMax: 'Llegaste al nivel máximo.',
    activitiesIntro: 'Consulta los talleres y sus horarios.',
    activitiesEmpty: 'Aún no hay talleres publicados.',
    interestsPromptTitle: '¿Qué carreras te interesan ahora?',
    interestsPromptBody: 'Elige hasta tres carreras que te interesaron hoy. Es opcional.',
    interestsTitle: 'Tus carreras de interés',
    interestsBody: 'Elige hasta tres y ordénalas por preferencia.',
    interestsSaved: 'Guardamos tus carreras de interés.',
    interestsClosed: 'La selección de carreras ya cerró.',
    closingTitle: 'Gracias por participar',
    closingBody: 'Gracias por participar en el Día OV. Tus carreras de interés quedaron guardadas.',
  },
  divisions: {},
};
